wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: huggingface
    huggingface_version: 4.6.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1633272922
    t:
      1:
      - 1
      - 3
      - 5
      - 11
      2:
      - 1
      - 3
      - 5
      - 11
      4: 3.9.5
      5: 0.12.0
      6: 4.6.0
      8:
      - 5
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 4
eps:
  desc: null
  value: 1.0e-08
lr:
  desc: null
  value: 2.0e-05
seed_val:
  desc: null
  value: 42
train_set_size:
  desc: null
  value: 0.7
